@startuml
'https://plantuml.com/sequence-diagram

[*] --> Connection
state Connection {
    [*] --> PerformConnection
    PerformConnection:Wait for endpoint to accept subscription
}

Connection-->ReceiveFrame


@enduml